steps:
  # build the container image
 - name: 'gcr.io/kaniko-project/executor:latest'
   args:
   - --destination=gcr.io/$PROJECT_ID/image
   - --cache=true
#   - --cache-ttl=672‬
  # push the container image to Container Registry
 - name: 'gcr.io/kaniko-project/executor:latest'
   args:
    - 'push'
    - 'asia.gcr.io/$PROJECT_ID/$_SERVICE_NAME'
  # Deploy container image to Cloud Run
 - name: 'gcr.io/cloud-builders/gcloud'
   args: 
   - 'beta'
   - 'run'
   - 'deploy'
   - '$_SERVICE_NAME'
   - '--image'
   - 'asia.gcr.io/$PROJECT_ID/$_SERVICE_NAME'
   - '--region'
   - 'asia'
   - '--platform'
   - 'managed'
   - '--quiet'
images:
  - asia.gcr.io/$PROJECT_ID/$_SERVICE_NAME
timeout: 14400s
