#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct. 

docker build --build-arg VCS_REF=`git rev-parse --short HEAD` \
  --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
  --build-arg VERSION=0.2 \
  --build-arg DOCKER_IMAGE=$IMAGE_NAME \
  --build-arg SOURCE_BRANCH=$SOURCE_BRANCH \
  --build-arg SOURCE_COMMIT=$SOURCE_COMMIT \
  -t $IMAGE_NAME .
